### ISSUE TITLE
Vet new indexer setup using data directory support

### ISSUE THREAD

**Issue by onetechnical** [algorand/indexer#1016]
## Problem

The upcoming release is going to implement data directory support for configurations. For a preview of this, see:

https://github.com/algorand/indexer/pull/1012/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

We should learn about these changes, as well as figure out how to implement in cluster.

## Solution

Set up a temporary indexer using an ephermeral DB, and experiment with setting up a new helm chart for this indexer install.

## Dependencies

Learning how to upgrade the helm chart for indexer for internal services.

## Urgency

Medium - High - needed before the next release.

**Comment by algobarb** [comment]
Modified the indexer image to include the data directory flag.
Created an empty directory and bulit the indexer image. Pushed the image to ECR and was able to successfully deploy it using helm.
The data directory stays empty. 
Stephen said in the future, we expect to write to the data dir and it would be stateful.

**Comment by algobarb** [comment]
I set up a meeting  to review the changes for ephemeral indexer helm chart/scripts/deployment. It kind of works, but I did have two concerns since it uses:
1. Stateful Sets instead of Deployment now, so there may need to be a process for deprecating before deploying the new indexers.
2. and it worked with gp2 storage class, but I had some issues getting gp3 working.

**Comment by algobarb** [comment]
Need to split the indexer reader and writer files. Writer will be a statefulset while reader can be a regular deployment.
