### ISSUE TITLE
DEB package missing user/group creation script

### ISSUE THREAD

**Issue by PSjoe** [algorand/indexer#111]
The DEB package for indexer-2.0 is missing a post-install script that creates the algorand user and group, as well as the home directory.  If you install it on a node that's all ready got the algorand package installed, that's all ready handled.  But if you install the indexer on its own, the default systemd init scripts won't work.  They assume a user "algorand" and group "algorand".

The following command creates the user correctly (at least on Ubuntu):

`useradd -r -m -d "/var/lib/algorand" algorand`

**Comment by ian-algorand** [comment]
@brianolson do you have any thoughts on this issue? We were just talking about it in grooming today.

**Comment by brianolson** [comment]
Since we don't auto-start the daemon but leave some configuration required I feel it would be inappropriate to do it automatically. Maybe this could be addressed by documentation with a few commands to copy-and-paste to achieve a simple setup?

**Comment by onetechnical** [comment]
It's a nice to have to auto-configure, and detect if these are already installed (i.e., have already installed the algorand package, and vice versa). The configuration requirement is an interesting consideration, though.

Maybe we should add to documentation as Brian suggests for now, since you can't just install-and-run yet?

**Comment by btoll** [comment]
I've found that the `preinst` maintainer script needs to be updated to not flag the `algorand-indexer` package.  This will need to be done in conjunction with this ticket.
