### ISSUE TITLE
Investigate invalid inner transaction json corruption.

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1314]
Investigate the root cause for #1292

Verify:
1. What caused the issue.
2. Whether or not it is fixed in current releases.

Create a unit test which would have detected the issue and verifies that the bug is fixed.

**Comment by AlgoStephenAkiki** [comment]
Investigate invalid inner transaction json corruption

Definitions

Inner transaction(s): A transaction that is contained within another transaction. 
As an example, an application call (which is a transaction) may contain a transaction within it.

Background

In the indexer database, the transaction table contains both regular and inner transactions.  Regular transactions have a transaction id and contain within them an array of inner transactions.  A copy of each of these inner transactions are also held in the same table in a separate row but have a null transaction id and only contain the inner transaction.


At some point, these separate inner transaction rows did not contain the inner transaction within the json but that of the parent (or root) transaction.  All other columns (such as the type enum column) are apparently correct for these transactions.


Testing Methodology

There is a potential fix that seems to have caused the bug to be resolved (hash: 2d47aa25519afb0a33bdfec83d27911325c609f2 - https://github.com/algorand/indexer/commit/2d47aa25519afb0a33bdfec83d27911325c609f2).  


To test that this commit fixes the issue, we first check to see what release was the first release to contain this hash, then go to one release before it to validate that the behavior is different.  In this case, the fix was first found in Indexer 2.9.0, so we go to Indexer 2.8.0 to confirm that we see corrupted inner transactions in the database.


Steps to Replicate

* Download the sandbox repo at https://github.com/algorand/sandbox
* Edit “config.source” to be the following:


export ALGOD_URL="https://github.com/algorand/go-algorand"
export ALGOD_BRANCH="master"
export ALGOD_SHA="b619b940e56165184c8e94bcbd13b656b773918c"
export NETWORK=""
export NETWORK_TEMPLATE="images/algod/DevModeNetwork.json"
export NETWORK_BOOTSTRAP_URL=""
export NETWORK_GENESIS_FILE=""
export NETWORK_NUM_ROUNDS=30000
export INDEXER_URL="https://github.com/algorand/indexer"
export INDEXER_BRANCH="develop"
export INDEXER_SHA="06e7ca8eec01f907474a50cc2072581c0e662ccb"
export INDEXER_DISABLED=""
export INDEXER_ENABLE_ALL_PARAMETERS="false"


* Launch a source build via “./sandbox up source -v”.  Note we are using go-algorand version 3.0.1(b619b940e56165184c8e94bcbd13b656b773918c) since it was the release that added inner transactions. 
* Wait for the sandbox to launch.
* Create “app.teal” in the sandbox directory and insert with the following program:
   * This program will create an application that contains an inner transaction


#pragma version 5
txn ApplicationID
bz end
itxn_begin
int acfg
itxn_field TypeEnum
int 1000000
itxn_field ConfigAssetTotal
int 3
itxn_field ConfigAssetDecimals
byte "oz"
itxn_field ConfigAssetUnitName
byte "Gold"
itxn_field ConfigAssetName
byte "https://gold.rush/"
itxn_field ConfigAssetURL
byte 0x67f0cd61653bd34316160bc3f5cd3763c85b114d50d38e1f4e72c3b994411e7b
itxn_field ConfigAssetMetadataHash
itxn_submit
end:
int 1
return


* Create “clear.teal” in the sandbox directory and insert with the following program:
#pragma version 5 
int 1
      


* Issue: 
   * ./sandbox copyTo app.teal
   * ./sandbox copyTo clear.teal
   * CREATOR=`./sandbox goal account list | awk 'NR==1{print $2}'`
      * Or just grab an account from the list command and set it to CREATOR
   * ./sandbox goal app create --approval-prog app.teal --clear-prog clear.teal --global-byteslices 0 --global-ints 0 --local-byteslices 0 --local-ints 0 --creator $CREATOR
   * ./sandbox goal clerk send -a 1000000000 -t WCS6TVPJRBSARHLN2326LRU5BYVJZUKI2VJ53CAWKYYHDE455ZGKANWMGM -f $CREATOR
   * ./sandbox goal app call --app-id 1 --from $CREATOR
* Wait for the indexer to index these transactions, this may take some time.  Issue the following and wait for the round to update:  curl "localhost:8980/health" 
* Then log into a psql shell: 
   * docker exec -it algorand-sandbox-postgres psql -h localhost -p 5432 -U algorand indexer_db 
* Issue the following query and validate that the rows returned is non-zero:
   * This query isolates inner transactions (since they will have a null transaction id) and sees if the transaction type is the same as a converted type enumeration.


Select * from (
select round, txid, intra, case typeenum
when 1 then 'keyreg'
when 2 then 'acfg'
when 3 then 'acfg'
when 4 then 'axfer'
when 5 then 'afrz'
when 6 then 'appl'
when 7 then 'stpf'
else '?' end type_col, txn->'txn' ->> 'type' as type_json from txn) as x where type_col != type_json and txid IS NULL;


Repeat this test with indexer 2.9.0 (hash: a0bcd4349dc2e173e7503f0fdc60759ab7073376) and validate that no rows are returned in the query.
