### ISSUE TITLE
Clarify documentation on configuration settings

### ISSUE THREAD

**Issue by jecassis** [algorand/indexer#194]
It is not entirely clear from the documentation (neither the README or developer.algorand.org) what the right combination of settings between `go-algorand` and `algorand-indexer` are. Specifically, when using `algorand-indexer` with `go-algorand` in archival mode is it really necessary to have `isIndexerActive` set to `true`? Is it redundant? Is it for backward-compatibility with `v1`? If we remove it would we support `v2` exclusively or would the `v2` indexer API endpoints also break? If both `algorand-indexer` and `isIndexerActive` are set are we supporting both `v1` and `v2` and wasting disk space unnecessarily? Some small elaboration on these points would be very helpful.

**Comment by brianolson** [comment]
Yeah, the old `algod` config.json "IsIndexerActive" filed is obsoleted by the standalone `algorand-indexer` and if your deployment isn't using the 2 APIs on `algod` that use the old indexer features in it, "IsIndexerActive" should be `false`

**Comment by ian-algorand** [comment]
Hey @ejbaran would you be able to help with this documentation issue?

**Comment by winder** [comment]
The documentation is here:
https://developer.algorand.org/docs/run-a-node/setup/indexer/

You can think of Indexer v1 and Indexer v2 as separate features. The documentation treats the installation that way as well which is why it doesn't mention setting `isIndexerActive` for the v2 setup.

You are correct with your questions. V1 is still around for backwards compatibility, you don't need to turn it on. If you had it on before, I don't think turning it off will free up the disk space.
