### ISSUE TITLE
enable searching by multiple address roles

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/indexer#210]
At it is, I cannot construct a query that that mentions two different addresses for different purposes.

**Comment by winder** [comment]
@jeapostrophe it's going to be easier to prioritize these if you describe the use case that you're having trouble with. Could you describe what you're trying to do so that I can better understand this request?

Maybe you're trying to search for transactions between two particular accounts? For example all transactions from account A to account B? There currently isn't a good way to do that.

Also, the sender and receiver roles are abstractions. For example "receiver" means the address matches payment receiver, asset receiver, payment close-to or asset close-to. How would you expect the proposed fields to act in these cases?

**Comment by jeapostrophe** [comment]
This abstraction of "sender" and "receiver" is not useful to me. I want to query the actual transaction parameters, as documented here --- https://developer.algorand.org/docs/reference/transactions/#common-fields-header-and-type

So when I say "sender", I mean the "snd" parameter in the codec. I don't mean the "asset sender", or the "asnd" parameter.

**Comment by winder** [comment]
You can search for the "snd" parameter by using the "sender" address-role and setting the transaction type to "pay".

**Comment by jeapostrophe** [comment]
Yes, thanks @winder. The problem is that I need to check the sender AND the receiver, but as I understand it, the way that the indexer works right now you can only use one address in one way. My request in this issue is to just expose all of the fields directly in the query API so I can craft my only query for whichever parameters of transactions I care about.

**Comment by gidonkatten** [comment]
I would like the ability to specify two addresses as well, for the sender and receiver

**Comment by gidonkatten** [comment]
Any updates on this?

**Comment by k13n** [comment]
Having the possibility to specify two addresses (sender & receiver) would indeed be helpful!
