### ISSUE TITLE
Support databases behind loadbalancers 

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#351]
## Summary
Currently, indexer assumes it talks to one database at a time. When connecting to a load balancer that has several readers behind, the API results may be incorrect because sometimes an API call can make more than one database call and these can end up on separate databases which may not be fully synced. 

## Scope/Requirements
There is a need to go over each of the API endpoints and, check which makes more than one database call, and make sure it happens on a single transaction to ensure the use of the same connection (and therefore the same db). 

## Urgency/Relative Priority
It's not time-critical but important to have in order to support that kind of deployment.

**Comment by brianolson** [comment]
Probably worth getting really specific about the topology here.

[multiple read-only indexers] - [one db]
This should be fine. There's only one view of the world, any read should be consistent.

[one or more indexers] - [postgres protocol proxy] - [multiple databases]
The proxy should understand transactions and keep multipart queries within a transaction together. Changing all the API calls to be one read-transaction could help this.

[api proxy] - multiple [one indexer + one database]
Transactionality of queries shouldn't matter. Like the first case one indexer talks to one db and gets one consistent view. We can't ensure that different API calls will hit the same indexer and could get two different answers on subsequent calls. API proxy may be able to turn on 'session affinity' where multiple queries from one source are more likely to go to the same backend.

**Comment by tolikzinovyev** [comment]
For reference, this is the list of things we need to fix.

- ~Fix most API endpoints~ #373
- Fix account rewinding (accounting/rewind.go)
- Fix accounting for importing blocks (importer/helper.go: updateAccounting()); should be fixed by #331
- Fix transaction paging (idb/postgres.go: Transactions()); it is possible that the user gets only some transactions for a round because of the limit, but the next Transactions() call will not return the rest of the transactions for this round

**Comment by tolikzinovyev** [comment]
@winder why closed? There are more items on the TODO list.

**Comment by tolikzinovyev** [comment]
New ticket for remaining issues: #461.
