### ISSUE TITLE
[Design] Refactor block import code

### ISSUE THREAD

**Issue by tolikzinovyev** [algorand/indexer#382]
## Summary
Currently, we import raw blocks with transactions and do accounting separately. This significantly complicates the code (and creates hard to catch bugs). The database has two counters, one for raw blocks and the other for accounting, and accounting needs to possibly catch up by processing multiple blocks at a time.

The proposal is to use only one counter in the database and write a new block, its transactions, and do accounting for it in the same database transaction.

## Scope/Requirements
**Scope of this issue will be to design a solution, we'll need to break this down into issues**

Refactoring should be straight-forward, but writing tests will take time. Ideally we will also have a single counter in the database, so we might change the db schema.

## Urgency/Relative Priority
Not urgent, but will significantly simplify future development of indexer.

**Comment by brianolson** [comment]
It was deliberately designed to happen in two phases for a few reasons.

- Some queries can be available immediately after the data is merely loaded. E.g. you can query your recent txn history immediately without dependency on what your current balance is. Your current balance is better served by `algod`
- It is possible to erase the accounting and recalculate it. If there are bugs in accounting they can be fixed by a reset (this pattern was used recently). Just loading the data takes a bunch of time and not redoing that saves a bunch of time.
- Accounting can be differently complicated and take a bunch of time; sometimes breaking up large operations makes the database run faster because it doesn't have to stage a bunch of provisional data for a transaction it's building up.
