### ISSUE TITLE
Empty reply from server for long running queries

### ISSUE THREAD

**Issue by winder** [algorand/indexer#385]
## Summary
When running a query that doesn't return immediately, the reply doesn't seem to be properly sent from the server.

For example, here is an API call attempting to page transactions on a busy account:
```
~$ curl -v "localhost:8981/v2/accounts/PRICEP3G2F5L6ZG5WTJIAKEQW4OJJ3FM4XVFQDZI7M2VBTFVUHTTR2AU2U/transactions?pretty&limit=50000&next=X-a9AAAAAAAnAAAA"|more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8981 (#0)
> GET /v2/accounts/PRICEP3G2F5L6ZG5WTJIAKEQW4OJJ3FM4XVFQDZI7M2VBTFVUHTTR2AU2U/transactions?pretty&limit=50000&next=X-a9AAAAAAAnAAAA HTTP/1.1
> Host: localhost:8981
> User-Agent: curl/7.58.0
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0* Empty reply from server
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

## Scope/Requirements
The results should be properly returned. If there is an actual timeout a proper error message should be returned.

## Urgency/Relative Priority
Since we have so many queries which don't perform well, this happens pretty often.

**Comment by winder** [comment]
Here is another call returning an empty reply:
```
/v2/accounts/5TSQNIL54GB545B3WLC6OVH653SHAELMHU6MSVNGTUNMOEHAMWG7EC3AA4?round=12618290
```

**Comment by mxmauro** [comment]
Hi, short history first. Yesterday we hit slowness on this query `/v2/transactions?asset-id=15477798&tx-type=acfg`

We fixed by creating this index `CREATE INDEX txn_by_asset ON public.txn USING btree (asset)`

But trying to track the issue I could see any configuration but the ones in `http.Server` object that leads to it. Also, in our server, the query is cancelled after 46 seconds, totally unrelated to the 10 seconds of the `ReadTimeout` and `WriteTimeout` parameters.

One of the things I'm suspecting is related to the `context` object passed to the database fetcher being cancelled (probably taking too much time because we see a similar value in postgres logs and `libpq` cancelling it) which, in turn, also cancels the http request.
