### ISSUE TITLE
Allow sorting of responses

### ISSUE THREAD

**Issue by chicopaec** [algorand/indexer#389]
It would be very helpful if some of the responses could be sorted by arbitrary fields. For example, to have the /transactions endpoint return the latest transactions by the block number, in descending order, so you can get the latest transactions without having to do any pagination.

**Comment by winder** [comment]
When filtering by account address results are returned oldest to newest, otherwise, they are returned newest to oldest.

For reference, I implemented this in a prototype while debugging something and we had some discussion: https://github.com/algorand/indexer/pull/283/files#diff-8fbec00be6e6b2f77a294cbe9a3ee8e3fbdcb5eb13be3046e5da8277302264c2L1400

**Comment by gidonkatten** [comment]
+1 this feature - in particular I would like to order the transactions for a given account and application from oldest to most recent. Since I use the account field, the responses are automatically ordered from most recent to oldest.

**Comment by ncherkas** [comment]
+1 to this, we've also faced a need to get transactions ordered by desc

**Comment by algodesk-io** [comment]
+1 to this feature.
It would be really helpful if we have sorted by field or at least the latest transactions.

**Comment by winder** [comment]
@chaihoang we need to clarify what we should support for this issue.

**Comment by algodesk-io** [comment]
Hi Team,

Do you have any plans to fix this issue ?

This is a critical requirement for my application (Explorer). 
https://app.dappflow.org

<img width="1777" alt="Screenshot 2022-09-27 at 8 03 46 PM" src="https://user-images.githubusercontent.com/65587162/192555985-e2291a32-d70e-49b3-8234-521a281d8481.png">

Attached is the screenshot of the asset overview page.
Older transactions pop up first and the user has to navigate back to the last page to look at the recent transactions of the asset.

This is a must-have if we want to build the indexer UI.

**Comment by chaihoang** [comment]
@algodesk-io It's not on the roadmap yet, but we are considering it. What are the use cases that would be most beneficial? Is it just sorting by newest transactions?

**Comment by algodesk-io** [comment]
> @algodesk-io It's not on the roadmap yet, but we are considering it. What are the use cases that would be most beneficial? Is it just sorting by newest transactions?

Yes, sorting by newest transactions for an asset, application, account, should solve 50% of the usecase.

remaining includes,
Sort by newest assets
Sort by newest applications

**Comment by algodesk-io** [comment]
@chaihoang Do you have any plans to support this?

**Comment by chaihoang** [comment]
@algoanne

**Comment by algoanne** [comment]
@algodesk-io with the refactoring of Indexer to use Conduit, supporting this type of feature might become possible. Sorting wouldn't be practical/performant if you were using an Indexer with full data, but if you used Conduit to filter out most of the data (just keeping data involving a certain app ID for example) then suddenly you can support more interesting queries without worrying so much about performance. 

That said, it's not in our near-term plan to work on this, just because of competing priorities. But, if someone was interested in adding this with an externally-contributed PR, we would welcome it.

**Comment by algoanne** [comment]
In this ticket, we will: 

enable sorting by most fields (ones that it makes sense to sort on), in either direction, for the transactions table only. New "order by" and "order direction" fields on the transactions endpoint. 

we will _disable_ pagination when using sorting, and work on pagination in a follow-up issue.
