### ISSUE TITLE
[Design] Query Performance: Process to Enable / Disable Indices

### ISSUE THREAD

**Issue by winder** [algorand/indexer#448]
One way to improve query performance is to create additional indices. Rather than enable all of them we should have a way to configure which ones should be enabled and the system can create them automatically.

This might be part of the config file, or a separate tool to work directly with the postgres database.

**Comment by Blackglade** [comment]
Currently running into issues trying to catchup my aurora serverless postgres db to the latest round in mainnet. Previously it was going very fast, but as I approached block 10.84 million, the insert rate slowed down to 4.4 blocks a second. Right now as it approaches 11 million, the rate has slowed down further to 3.0 blocks a second. 

This is obviously a big problem as the rate at which these insertions decreases, catching up to mainnet will be an almost impossible task. Is there anything I can do increase the performance of the indexer?

I've tried setting `enable_indexscan` to off in hopes that it might help but to no avail. I've also attempted trying to disable indexes for the tables in hopes it will speed up insertion but have been issues due to aurora's permission restrictions.
