### ISSUE TITLE
Update endpoints to handle uncapped assets & apps 

### ISSUE THREAD

**Issue by algoanne** [algorand/indexer#828]
**Context**
We are about to remove existing limits on the number of assets and apps an address can create and opt in to. The indexer account lookup endpoint will now potentially need to return a lot more information.

**What are you looking for?**
All indexer endpoints should continue to function and be performant after the assets & apps uncapping. 

**(Optional) Design considerations**
pagination is suggested.

**Comment by agodnic** [comment]
This is already problematic in `GET /v2/accounts/{address}` because the `include-all` parameter fetches all the historic state for an account. Thus, the size of the arrays `assets`, `apps-local-state`, `created-assets`, and `created-apps` is effectively unbounded.

Example: https://algoindexer.algoexplorerapi.io/v2/accounts/CJKWVV7YJMHFJINFCDETDSSN4DP2MRP5WJCE6WUJ2PXBH4NNL7BJCO7YDM?include-all=true

Pagination would solve this issue
