### ISSUE TITLE
New endpoint to get all boxes for an application (and other necessary work to support boxes in indexer)

### ISSUE THREAD

**Issue by algoanne** [algorand/indexer#978]
(WIP) 

### Problem
Dapp devs should be able to get all of a contract’s boxes using the indexer. This can be useful, for example, for display purposes (functioning of the front-end), analytics purposes, or when deleting the dapp and wanting to recover all minimum balance requirements. 

### Solution
an indexer endpoint to get all boxes for an application ID.
this likely will require creating a new table for boxes. 

**questions**: 
what order are they returned in? 
pagination to be performant?
note that the boxes will have different sizes

**Comment by winder** [comment]
What is a box?

**Comment by algoanne** [comment]
@winder yes definitely (I think) will need a new table as well. I can update the title & description so that's more explicitly understood.

**Comment by michaeldiamant** [comment]
Closing in favor of https://github.com/algorand/go-algorand/issues/3973 because we agreed it's sufficient to start with an algod-only approach.  

Rationale:
* Indexer does _not_ support _rewind_ capabilities for existing Application state (local + global storage).  Its APIs support retrieving Application state as of query time.  
* Since the initial objective is to provide parity with existing facilities, and because it's conceivable to provide _as of query time_ APIs in algod, we're opting to start in algod.  The intent is to reduce duplicative efforts between algod and indexer.

**Comment by michaeldiamant** [comment]
Re-opening - For parity with other offered APIs, we're opting to expose indexer APIs.  Updating the description with proposed APIs.
